-- Migration: add ai_generated boolean to proofreading_concerns
-- Adds an explicit flag to record whether a concern was generated by an AI service
ALTER TABLE IF EXISTS proofreading_concerns
  ADD COLUMN IF NOT EXISTS ai_generated boolean NOT NULL DEFAULT false;

-- Add an index to make queries by provenance efficient
CREATE INDEX IF NOT EXISTS idx_proofreading_concerns_ai_generated
  ON proofreading_concerns (ai_generated);
